config/routes.rb
Rails.application.routes.draw do
  
  resources :accounts, only: [:index] do 
    collection do
      post :import
    end
  end
  
  resources :items
  resources :infobooks
  resources :books_dbs
  resources :articles
  resources :articles
  resources :products

  
  root 'pages#home'
  get '/home', to: 'pages#home'
  get '/search', to: 'products#search'
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  
end

app/models/books_db.rb
class BooksDb < ActiveRecord::Base
end

app/controllers/books_d_bs_controller.rb
class BooksDBsController < ApplicationController
  before_action :set_books_db, only: [:show, :edit, :update, :destroy]

  # GET /books_dbs
  # GET /books_dbs.json
  def index
    @books_dbs = BooksDb.all
  end

  # GET /books_dbs/1
  # GET /books_dbs/1.json
  def show
  end

  # GET /books_dbs/new
  def new
    @books_db = BooksDb.new
  end

  # GET /books_dbs/1/edit
  def edit
  end

  # POST /books_dbs
  # POST /books_dbs.json
  def create
    @books_db = BooksDb.new(books_db_params)

    respond_to do |format|
      if @books_db.save
        format.html { redirect_to @books_db, notice: 'Books db was successfully created.' }
        format.json { render :show, status: :created, location: @books_db }
      else
        format.html { render :new }
        format.json { render json: @books_db.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books_dbs/1
  # PATCH/PUT /books_dbs/1.json
  def update
    respond_to do |format|
      if @books_db.update(books_db_params)
        format.html { redirect_to @books_db, notice: 'Books db was successfully updated.' }
        format.json { render :show, status: :ok, location: @books_db }
      else
        format.html { render :edit }
        format.json { render json: @books_db.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books_dbs/1
  # DELETE /books_dbs/1.json
  def destroy
    @books_db.destroy
    respond_to do |format|
      format.html { redirect_to books_dbs_url, notice: 'Books db was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_books_db
      @books_db = BooksDb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def books_db_params
      params.require(:books_db).permit(:title, :isbn, :author, :publisher, :rating, :descripton, :image_link)
    end
end

app/helpers/books_d_bs_helper.rb
module BooksDBsHelper
end

app/views/books_d_bs/_form.html.erb
<%= form_for(@books_db) do |f| %>
  <% if @books_db.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@books_db.errors.count, "error") %> prohibited this books_db from being saved:</h2>

      <ul>
      <% @books_db.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :descripton %><br>
    <%= f.text_area :descripton %>
  </div>
  <div class="field">
    <%= f.label :image_link %><br>
    <%= f.text_field :image_link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books_d_bs/edit.html.erb
<h1>Editing Books_db</h1>

<%= render 'form' %>

<%= link_to 'Show', @books_db %> |
<%= link_to 'Back', books_dbs_path %>

app/views/books_d_bs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books_dbs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Isbn</th>
      <th>Author</th>
      <th>Publisher</th>
      <th>Rating</th>
      <th>Descripton</th>
      <th>Image link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books_dbs.each do |books_db| %>
      <tr>
        <td><%= books_db.title %></td>
        <td><%= books_db.isbn %></td>
        <td><%= books_db.author %></td>
        <td><%= books_db.publisher %></td>
        <td><%= books_db.rating %></td>
        <td><%= books_db.descripton %></td>
        <td><%= books_db.image_link %></td>
        <td><%= link_to 'Show', books_db %></td>
        <td><%= link_to 'Edit', edit_books_db_path(books_db) %></td>
        <td><%= link_to 'Destroy', books_db, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Books db', new_books_db_path %>

app/views/books_d_bs/new.html.erb
<h1>New Books_db</h1>

<%= render 'form' %>

<%= link_to 'Back', books_dbs_path %>

app/views/books_d_bs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @books_db.title %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @books_db.isbn %>
</p>

<p>
  <strong>Author:</strong>
  <%= @books_db.author %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @books_db.publisher %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @books_db.rating %>
</p>

<p>
  <strong>Descripton:</strong>
  <%= @books_db.descripton %>
</p>

<p>
  <strong>Image link:</strong>
  <%= @books_db.image_link %>
</p>

<%= link_to 'Edit', edit_books_db_path(@books_db) %> |
<%= link_to 'Back', books_dbs_path %>