config/routes.rb
Rails.application.routes.draw do
  
  resources :accounts, only: [:index] do 
    collection do
      post :import
    end
  end
  
  resources :items
  resources :infobooks
  resources :books_dbs
  resources :articles
  resources :articles
  resources :products

  
  root 'pages#home'
  get '/home', to: 'pages#home'
  get '/search', to: 'products#search'
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # POST /items
  # POST /items.json


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
9780199795277    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :isbn, :authors, :publisher, :average_rating, :image_link)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :authors %><br>
    <%= f.text_field :authors %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :average_rating %><br>
    <%= f.number_field :average_rating %>
  </div>
  <div class="field">
    <%= f.label :image_link %><br>
    <%= f.text_field :image_link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Isbn</th>
      <th>Authors</th>
      <th>Publisher</th>
      <th>Average rating</th>
      <th>Image link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items = GoogleBooks.search(params[:q], {:count => 18}) %>
    <% @items.each do |item| %>
      <%unless item.isbn.nil? || item.image_link.nil? %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.isbn %></td>
        <td><%= item.authors %></td>
        <td><%= item.publisher %></td>
        <td><%= item.average_rating %></td>
        <td><%= link_to image_tag(item.image_link), item_path(item.isbn) %></td>
        <td><%= item.categories %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @item.isbn %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @item.authors %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @item.publisher %>
</p>

<p>
  <strong>Average rating:</strong>
  <%= @item.average_rating %>
</p>

<p>
  <strong>Image link:</strong>
  <%= @item.image_link %>
</p>

<%= form_tag(import_accounts_path, :method => "post", class: "navbar-form", id: "search-form") do %>
<div class="input-append">
<%= text_field_tag :isbn, params[:isbn], class: "span2", placeholder: "Search Articles" %>
<!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
   of using a Rails form helper -->
<button class="btn" type="submit"><i class="icon-search"></i></button>
</div>
<% end %>